### ISSUE TITLE
PSA: Newer releases leave WoW.exe running after exit on OS earlier than Win10

### ISSUE THREAD

**Issue by AyrianaWoW** [allfoxwy/UnitXP_SP3#7] opened 2024-12-06 06:36 UTC
Putting it here so people experiencing the issue are aware of it prior to it being fixed.

All releases starting from Nov 11th 2024 and older are working fine.
The issue happens starting with the release on Nov 23rd and persisting into the November 29th release.

Bug description: After exiting the game via 'Exit Game' button through in-game menu or main 'Quit' button on main menu the 'WoW.exe' client still shows up as a background process in Windows Task Manager and must be forcefully-terminated via 'End Task' to free up resources that the game used.  If running and exiting the game multiple times, each 'phantom' process remains and refuses to free up resources until force-terminated.

Tested on completely clean/fresh WoW install both with and without UnitXP SP3 installed/configured.  Narrowed down the issue to the one starting on Nov 23rd so the bug was introduced sometime from Nov 12th or later.  There are 10 potential commits in that timeframe (between Nov 12th and Nov 23rd) that could be the cause of the bug.

Reproduction steps:

- Start WoW.exe
- Exit WoW.exe
- Process shows up in 'Windows Task Manager', must use 'End Task' to terminate it or it will keep hogging resources.

**Comment by allfoxwy** [comment] 2024-12-06 15:37
It sounds like Timer thread didn't release after WoW.exe main thread quit. I would check on it.

**Comment by allfoxwy** [comment] 2024-12-07 15:26
I couldn't reproduce this issue on Windows 11 and Debian Linux.
However could you try if this version works? [UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18048919/UnitXP_SP3.dll.zip)

We may need a few more experiment at your side trying to find  a cure.

**Comment by AyrianaWoW** [comment] 2024-12-09 19:27
> I couldn't reproduce this issue on Windows 11 and Debian Linux. However could you try if this version works? [UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18048919/UnitXP_SP3.dll.zip)
> 
> We may need a few more experiment at your side trying to find a cure.

Unfortunately this DLL is also bugged, it even bugs out with the Nov 11th files so there's something that is messing it up, likely the 'timer' functionality.

**Comment by allfoxwy** [comment] 2024-12-13 08:02
Hey I think I found something, could you try this one please?  [UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18123203/UnitXP_SP3.dll.zip)

**Comment by AyrianaWoW** [comment] 2024-12-15 17:27
> Hey I think I found something, could you try this one please? [UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18123203/UnitXP_SP3.dll.zip)

Yeah this one doesn't work either, RIP.
I figure at this point just let people know about the bug and to check to close the orphaned WoW.exe process after exiting the game. I appreciate your help and assistance in taking time to do all this, but it may just need to be something deprecated as a bug for a tiny % of players.

**Comment by allfoxwy** [comment] 2024-12-17 10:33
K another version: [test-UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18163894/test-UnitXP_SP3.dll.zip)

This time we need a bit more test.
Could you try all 3 tests and tell me if they would trigger the bug please:

#### Test 1
- Run the game with UnitXP SP3
- Use `Exit Game` or `Quit` in-game button normally.

#### Test 2
- Run the game with UnitXP SP3
- After log into game world, input a command in chat `/script UnitXP("timer","arm", 2000, 2000,"print")`
- Use `Exit Game` or `Quit` in-game button normally.

#### Test 3
- Run the game with UnitXP SP3
- After log into game world, input a command in chat `/script UnitXP("timer","arm", 2000, 2000,"print")`
- Use ALT+F4 to interrupt the game.

**Comment by AyrianaWoW** [comment] 2024-12-17 21:49
FISSION MAILED! <3

Performed all 3 tests and no more orphan WoW.exe process! YAY!

The last one of doing alt-f4 gave me an 'unhandled exception' error dialog box and then exited out when I acknowledged the error by clicking OK.

Whether I use 'Exit Game' in-game or 'Quit' on the title screen the result is the same, no orphans!

**Comment by allfoxwy** [comment] 2024-12-19 08:10
Now it should be fixed for both normal exit and ALT-F4.

Reference fix is 55d35251fe056f6f2932cdd967fcd83a523e5b7d

This fix would be in next release, meanwhile you could use this: [fixed-issue7-UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/18194484/fixed-issue7-UnitXP_SP3.dll.zip)

It took some time but we made it. A complete fix with no compromise. Thanks for your report and all the patient to test! @AyrianaWoW

**Closed** 2024-12-19 08:10 UTC
Labels: bug, can't reproduce
